/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_panayotis_appenh_MacEnhancer */

#ifndef _Included_com_panayotis_appenh_MacEnhancer
#define _Included_com_panayotis_appenh_MacEnhancer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_panayotis_appenh_MacEnhancer
 * Method:    registerUpdate0
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/Runnable;)V
 */
JNIEXPORT void JNICALL Java_com_panayotis_appenh_MacEnhancer_registerUpdate0
  (JNIEnv *, jobject, jstring, jstring, jobject);

#ifdef __cplusplus
}
#endif
#endif
