/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_panayotis_appenh_MacEnhancer */

#ifndef _Included_com_panayotis_appenh_MacEnhancer
#define _Included_com_panayotis_appenh_MacEnhancer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_panayotis_appenh_MacEnhancer
 * Method:    registerUpdate0
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/Runnable;)V
 */
JNIEXPORT void JNICALL Java_com_panayotis_appenh_MacEnhancer_registerUpdate0
  (JNIEnv *, jobject, jstring, jstring, jobject);

/*
 * Class:     com_panayotis_appenh_MacEnhancer
 * Method:    showOpenDialog
 * Signature: (Ljava/lang/String;Ljava/lang/String;ZZLcom/panayotis/appenh/MacEnhancer/FileDialogCallback;)V
 */
JNIEXPORT void JNICALL Java_com_panayotis_appenh_MacEnhancer_showOpenDialog
  (JNIEnv *, jobject, jstring, jstring, jstring, jboolean, jboolean, jboolean, jobject);

/*
 * Class:     com_panayotis_appenh_MacEnhancer
 * Method:    showSaveDialog
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Lcom/panayotis/appenh/MacEnhancer/FileDialogCallback;)V
 */
JNIEXPORT void JNICALL Java_com_panayotis_appenh_MacEnhancer_showSaveDialog
  (JNIEnv *, jobject, jstring, jstring, jstring, jstring, jobject);


/*
 * Class:     com_panayotis_appenh_MacEnhancer
 * Method:    getThemeName
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_panayotis_appenh_MacEnhancer_getThemeName
  (JNIEnv *, jobject);

/*
 * Class:     com_panayotis_appenh_MacEnhancer
 * Method:    registerThemeChanged0
 * Signature: (Lcom/panayotis/appenh/Enhancer/ThemeChangeListener;)V
 */
JNIEXPORT void JNICALL Java_com_panayotis_appenh_MacEnhancer_registerThemeChanged0
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
